name: Prerelease
run-name: ${{ github.event_name }} by ${{ github.actor }} to ${{ github.ref }}
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run dev
      - run: ls ${{ github.workspace }}
