name: Prerelease
run-name: ${{ github.event_name }} by ${{ github.actor }} to ${{ github.ref }}
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run dev
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: '${{ github.event.repository.name }}.zip'
          exclusions: '/.git /.github /node_modules'
      - run: ls -la ${{ github.workspace }}
